---
model_name: z1_ppo_opt
model: PPO
save_freq: 500_000
env:
  n_envs: 8
  n_stack: 3
model_kwargs:
  policy: CnnPolicy
  n_steps: 128
  n_epochs: 20
  batch_size: 128
  learning_rate: 0.00015
  gamma: 0.99
  gae_lambda: 0.8
  clip_range: 0.1
  vf_coef: 0.95
  max_grad_norm: 0.6
  ent_coef: 8.0e-6
  policy_kwargs:
    activation_fn: leaky_relu
    ortho_init: false
learn_kwargs:
  total_timesteps: 1_000_000
  log_interval: 1
