---
model_name: z8_sevs_1hp
model: PPO
save_freq: 500_000
env:
  boss: 8
  n_envs: 16
  n_stack: 5
model_kwargs:
  policy: CnnPolicy
  # learning_rate: lin_2.5e-4
  learning_rate: 2.5e-4
  n_steps: 128
  batch_size: 512
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.1
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null
  policy_kwargs:
    net_arch: null
    ortho_init: true
    normalize_images: true
    optimizer_kwargs:
      eps: 1.0e-7
learn_kwargs:
  total_timesteps: 10_000_000
  log_interval: 1
